"""empty message

Revision ID: 586cd296737b
Revises: 43fa78bc3b7d
Create Date: 2024-10-29 12:56:52.837991

"""
from alembic import op
import models as models
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '586cd296737b'
down_revision = '43fa78bc3b7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_public_providers',
    sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('icon', sa.String(length=255), nullable=False),
    sa.Column('schema', sa.Text(), nullable=False),
    sa.Column('schema_type_str', sa.String(length=40), nullable=False),
    sa.Column('user_id', models.types.StringUUID(), nullable=False),
    sa.Column('tenant_id', models.types.StringUUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tools_str', sa.Text(), nullable=False),
    sa.Column('credentials_str', sa.Text(), nullable=False),
    sa.Column('privacy_policy', sa.String(length=255), nullable=True),
    sa.Column('custom_disclaimer', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='tool_public_provider_pkey'),
    sa.UniqueConstraint('name', 'tenant_id', name='unique_public_tool_provider')
    )
   

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tool_public_providers')
    # ### end Alembic commands ###
